---
title: "STAT1601-003_hw1"
author: "Kyndal Harrison"
date: "1/21/2020"
output: pdf_document
---

# Question 1

```{r}
Homework = 94.3 * .3
Exam1 = 86.1 * .2
Exam2 = 88.5 * .2
FinalProject = 83 * .3

FinaLGrade = Homework + Exam1 + Exam2 + FinalProject
FinaLGrade

print( "Final Grade of 88.11 is a B+" )
```



# Question 2

(a) False
(b) False
(c) True
(d) True
(e) True
(f) False
(g) False
(h) True
(i) True
(j) True




# Question 3

(a)
```{r}
LineQs =  c( "Q1", "Q1", "Q1", "Q1" )
print( LineQs )
```
(b)
```{r}
FirstLines = c( 50.0, 52.5, 55.0, 57.5, 60.0, 62.5, 65.0, 67.5, 70.0, 72.5, 75.0, 77.5, 80.0, 82.5, 85.0, 87.5, 90.0, 92.5, 95.0, 97.5, 100.0)

print( FirstLines )
```
(c)
```{r}
thousandyears = c( 2010, 2010, 2010, 2010, 2011, 2011, 2011, 2011, 2012, 2012, 2012, 2012, 2013, 2013, 2013, 2013, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017) 
print( thousandyears )
```
(d)
```{r}
lastyears = c( 2016, 2016, 2016, 2016, 2017, 2017, 2017)
print( lastyears )
```
(e)
```{r}
random = c( 1295, 1296, 1297, 1298, 1299, 1298, 1297, 1296, 1295, 1294, 1293, 1292, 1291, 1290)
print( random )
```
(f)
```{r}
fours = c(4160, 4055, 3950, 3845, 3740, 3635, 3530)
print( fours )
```



# Question 4 
```{r}
ClassData = read.csv("/Users/kyndalharrison/STAT1601/Class Materials/ClassData.csv")
table(ClassData$Sport)
```



# Question 5
```{r}
library( nycflights13)
summary( flights$dep_delay, na.rm = NULL)

```

